### PR TITLE
Implements a BLE service for rendering images

### PR DESCRIPTION
**Pull request by rbaron**
This PR adds a BLE service & characteristic to which clients can write raw bitmaps.

Here's a sample of uploading an image with [rbaron/pricetag-printer](https://github.com/rbaron/pricetag-printer):

image

### CODE REVIEW

**Comment by atc1441** [comment]
Added a veeery simple WebBluetooth Image uploader for it.

https://atc1441.github.io/ATC_TLSR_Paper_Image_Upload.html

its super crude but does its work for now, can definitely be made more convenient :D

**Comment by rbaron** [comment]
That's amazing! It works for me already 🚀

image

**Comment by atc1441** [comment]
Great :)

As you also see the last line is not send correctly, but will be looked into it in the future

**Comment by atc1441** [comment]
did increased the size checking from your upload code now
https://github.com/atc1441/ATC_TLSR_Paper/blob/main/Firmware/src/epd_ble_service.c#L41

now its fully uploading an image via the WebUploader

that did prevent the full image from being accepted so the last line.

as we got 122 pixel it is not a full byte as far i understand and it has something todo with that, but not sure right now ^^

what do you think about that.

**Comment by bitbank2** [comment]
The buffer layout is really 128x250 with 122x250 visible

**Comment by rbaron** [comment]
Yes, that's my understanding too. 6 bits of each row are not used, but still needed because the buffer is byte-padded per row.

So I think the [code here](https://github.com/atc1441/ATC_TLSR_Paper/blob/main/Firmware/src/epd_ble_service.c#L41) does not need the `+ 1` at the end, otherwise we run the risk of writing past the `image` buffer.

**Comment by atc1441** [comment]
The WebUploader is "patching" each last byte as well, so will look into why the last image transmission does exceed the buffer check.

As the +1 did made it work it means only one byte is send too much

From the console log you can see it sends not to much if you want to see

**Comment by rbaron** [comment]
@atc1441 you are right! There should indeed be a `+1` there (or change the condition to `>` instead of `>=`). Because we increment the `byte_pos` by the amount of image data written to `image`, it always point to the _next_ position that will be written. At the end of the process, it should point to exactly `sizeof(image)`. So the condition `byte_pos == sizeof(image)` is actually valid, and we should not return early from the function.

Example: if the buffer size is 4 and we write 4 bytes to it, `byte_pos` will be equal to 4 and all is good.

Nice catch!

**Pull request merged**
